name: SkStuff
author: [TheBukor, Govindas]
description: A Skript addon which adds extra functionalities such as pathfinder goals.
version: 1.6.4.2-fork-1.13-1.14
main: me.TheBukor.SkStuff.SkStuff
softdepend: [Skript]
