name: SkPathfinderGoals
authors: [TheBukor, Govindas]
description: A Skript addon which adds extra functionalities such as pathfinder goals.
version: "2.0"
main: me.TheBukor.SkStuff.SkStuff
softdepend: [Skript]